# Adapted from: https://github.com/pytries/marisa-trie/blob/master/.github/workflows/build-and-publish.yml
# and: https://github.com/pypa/cibuildwheel/blob/main/examples/github-deploy.yml

name: Build & Publish

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: python -m pip install Cython~=0.29 pytest
      - name: Build source distribution
        run: python setup.py sdist
      - name: Install source distribution
        run: python -m pip install dist/pe-*.tar.gz
      - name: Test source distribution
        run: pytest test/
      - name: Store the source distribution
        uses: actions/upload-artifact@v2
        with:
          name: python-package-distributions
          path: dist
          retention-days: 4

  build-wheels:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] # , windows-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
      # - name: Install build dependencies
      #   run: python -m pip install --upgrade cython
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.2.0a1
        env:
          CIBW_SKIP: "pp*" # skip Pypy wheels
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: "pytest {project}/test/"
      - uses: actions/upload-artifact@v2
        with:
          name: python-package-distributions
          path: ./wheelhouse/*.whl

  # publish:
  #   needs:
  #     - os-built-distributions
  #     - source-distribution
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Download all the dists
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: python-package-distributions
  #         path: dist/
  #     - name: To be published
  #       run: ls -l dist
  #     - name: Publish
  #       if: github.event.inputs.branch != ''
  #       uses: pypa/gh-action-pypi-publish@release/v1.4.2
  #       with:
  #         user: __token__
  #         password: ${{ secrets.PYPI_PASSWORD }}
  #         skip_existing: true
